server:
  port: 5000
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization : true

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  file.name: logs/application.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.example: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR
logback:
  rollingpolicy:
    file-name-pattern: logs/application-%d{yyyy-MM-dd}.log
    max-file-size: 10MB
    max-history: 7